"""adiciona encaminhamento de atendimentos

Revision ID: 2a9837209702
Revises: 0003
Create Date: 2026-08-18 16:00:54.924906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9837209702'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimentos', sa.Column('atendimento_origem_id', sa.Integer(), nullable=True))
    op.add_column('atendimentos', sa.Column('tipo_finalizacao', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_atendimentos_atendimento_origem_id'), 'atendimentos', ['atendimento_origem_id'], unique=True)
    op.create_foreign_key(None, 'atendimentos', 'atendimentos', ['atendimento_origem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atendimentos', type_='foreignkey')
    op.drop_index(op.f('ix_atendimentos_atendimento_origem_id'), table_name='atendimentos')
    op.drop_column('atendimentos', 'tipo_finalizacao')
    op.drop_column('atendimentos', 'atendimento_origem_id')
    # ### end Alembic commands ###
